# FROM node:alpine
# WORKDIR '/app'
# COPY package.json .
# RUN npm install
# COPY . .
# CMD ["npm", "run", "start"]

## UPDATES MARCH 2021
# FROM node:alpine
# USER node
# RUN mkdir -p /home/node/app
# WORKDIR /home/node/app
# COPY --chown=node:node ./package.json ./
# RUN npm install
# COPY --chown=node:node ./ ./
# CMD ["npm", "start"]

# UPDATES MARCH 2022

FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
